### ISSUE TITLE
Syntax Errors and completion failure

### ISSUE THREAD

**Issue by tferr** [fiji/jython-autocompletion#3]
@acardona, tried a couple of things (albeit not thoroughly due to lack of time). Came across one issue within if blocks. Here is a MWE:

```python
from ij import ImagePlus

def run():

    imp = ImagePlus("http://imagej.nih.gov/ij/images/clown.gif")
    # imp. ## completion works here
    if not imp:
       # imp.   ## autocompletion fails
       print("path is not valid")
    else:
       # imp.   ## autocompletion fails
       imp.show()

run()
```
- On line 6 (before the if condition). Autocompletion works as expected (`Python module ij.ImagePlus doesn't have an associated file path.` printed to Console)
- Autocompletion on lines 9 or 11 fails
- Also, it gives me the impression that hitting Ctrl+space repeatedly when there are no suggestions leads to (understandably) syntax errors, e.g.:
```
SyntaxError: mismatched input '\n' expecting set null
  File "<none>", line 7
    imp.
       ^
```

**Comment by acardona** [comment]
Try again, just pushed a number of fixes and additionally supported code block types.

**Comment by tferr** [comment]
I have a hard deadline on the 17th. Will look after it (probably on the 19-20th weekend).
