### ISSUE TITLE
The import org.scijava.ui.swing.script.autocompletion.CompletionText cannot be resolved

### ISSUE THREAD

**Issue by ZhaoJK** [fiji/jython-autocompletion#6]
Hi, 

When trying to make a package, it failed with "org.scijava.ui.swing.script.autocompletion.CompletionText cannot be resolved". 
I checked script-editor 0.5.8 - 0.5.10, it did not contain class CompletionText. Is there any tips?

Thanks!

**Comment by acardona** [comment]
Indeed, this is now fixed. There was a long-standing pull request in the script-editor repository that is now merged, so it all compiles.

I'm aiming at releasing this package to the Fiji updater asap.

**Comment by acardona** [comment]
Note: the jython autocompletion functionality is now live in the Fiji updater. Do please give it a try if you can. It's limited but quite functional.
